### ISSUE TITLE
nginx "504 Gateway Time-out" error for dashboard/attacks pages

### ISSUE THREAD

**Issue by ch40s** [pwnlandia/mhn#32]
When I open "ui/dashboard/" or "/ui/attacks/" pages I get "504 - Gateway time-out" errors while navigating through the rest of the site I don't have any problem. 
I have 1 sensor connected with 356 attacks logged.

The error.log of nginx contains the following lines:

2014/07/18 13:48:30 [error] 3068#0: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: A.B.C.D, server: _, request: "GET /ui/dashboard/ HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "127.0.0.1:X"
2014/07/18 13:55:48 [error] 3107#0: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: A.B.C.D, server: _, request: "GET /ui/attacks/ HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "127.0.0.1:X"

I tried restarting the nginx and other services, I increased some thresholds in nginx.conf, I rebooted the server, I added "proxy_read_timeout 150;" in "/etc/nginx/sites-available/default" under "location @mhnserver" but none of the above resolved the problem.

**Comment by crypt0b0y** [comment]
@ch40s thank you for finding solution! Can you please give an example code utils.py with proxy? I dont understand where i need to specified it :+1:
