### ISSUE TITLE
504 gateway timeout

### ISSUE THREAD

**Issue by gamba** [pwnlandia/mhn#694]
I installed MHN from git repository on a fresh Ubuntu 18.04, with no ELK / Splunk / Firewall rules. The installation works fine. Logging in the webapp and deploying honeypots works fine too: i deployed two Ubuntu/Snort sensors. 

The MHN webapp stops to work after the first attack is received, ngingx returns 504 gateway timeout. 

As information: 
- the ubuntu machine has enough resources to run (memory, disk, cpu)
- it was a fresh install and deployment of HP works fine
- i do not see anything suspicious in the logs
- rebooting the machine / restarting the services doesn't help

(it seems i'm not the only one having this problem (last post): https://groups.google.com/forum/#!topic/modern-honey-network/WWs9RCgvqjc)

**Comment by nitrogen17** [comment]
what sensor did you use? and how did you mitigate your first attack?

**Comment by gamba** [comment]
> what sensor did you use? and how did you mitigate your first attack?

- a ubuntu / snort: installation went fine, the sensor connected port 10000 on the MHN.
- there was no mitigation ("attack" was a portscan).

**Comment by vtod** [comment]
I am facing similar issue. After debugging, looks like there is a problem related to specific mongodb find command. Let me explain:
If I request page "View Sensors", then it performs count query, and total number of attacks is shown. But, if I click to "Attacks" then it causes timeout and everything stops. 
After restarting  uwsgi with command "supervisorctl restart mhn-uwsgi" then web interface starts working again till next click on "Attacks". 
Based on debug done with mongodb, the last command executed against mongodb was:
2019-08-11T20:36:30.176+0000 I COMMAND  [conn16] command mnemosyne.session command: find { find: "session", filter: {}, sort: { timestamp: -1 }
, limit: 10, lsid: { id: UUID("8eb867b0-e6c2-435c-9b0d-2f09c1e40b56") }, $db: "mnemosyne", $readPreference: { mode: "primaryPreferred" } } plan
Summary: COLLSCAN keysExamined:0 docsExamined:32 hasSortStage:1 cursorExhausted:1 numYields:0 nreturned:10 reslen:2390 locks:{ Global: { acquir
eCount: { r: 2 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 1 } } } protocol:op_msg 0ms

Dropping of database mnemosyne does not help - it will create a new collection, counters of attacks against registered sensors will work, but again mhn-uwsgi will stop working on first click on "Attacks"

**Comment by gamba** [comment]
@vtod i agree with the queries, nevertheless i re-run the queries you mentioned for my sensors on my mongo, and the queries themselves aren't slow-queries. 
The problem seems to be related in how mhn-uwsgi handle the result of the query.

**Comment by IQooLogic** [comment]
The thing that was problematic is http get request to _https://geospray.threatstream.com/ip/_ in method called __get_flag_ip(ipaddr)_ in file _mhn/server/mhn/ui/utils.py_.

Making method _get_flag_ip(ipaddr)_ return default flag fixed the problem.

**Comment by StratoZen** [comment]
This was actually the issue for me as well. Most of the UI elements just returned 504 because of this. Seems like the Geo IP lookup service utilized above is no longer in service? Perhaps utilizing a local DB of country / IP mapping is preferable, with an option to update on a regular basis.

**Comment by robevans2** [comment]
This was actually the issue for me as well. Most of the UI elements just returned 504 because of this. Seems like the Geo IP lookup service utilized above is no longer in service? Perhaps utilizing a local DB of country / IP mapping is preferable, with an option to update on a regular basis.

**Comment by gamba** [comment]
@IQooLogic thank you, that's actually the problem. 

as a quick solution, adding `127.0.0.1	geospray.threatstream.com` to ` /etc/hosts` solved the problem. I find a pity that despite Geolite being installed, all IPs are transmitted to geospray.threatstream.com.

**Comment by Jdelgado89** [comment]
> The thing that was problematic is http get request to _https://geospray.threatstream.com/ip/_ in method called __get_flag_ip(ipaddr)_ in file _mhn/server/mhn/ui/utils.py_ which blocks execution.
> 
> Making method _get_flag_ip(ipaddr)_ to always return default flag fixed the problem (domain is down!).
> 
> Hope this helps :)

I am experiencing the same issue, I am not a programmer can please explain how you accomplished this. That would be greatly appreciated. Thank you.

**Comment by z0n3z3r0** [comment]
@Jdelgado89 the TLDR is MHN tries to lookup the source country for each public IP seen hitting a honeypot, but because the geospray service at threatstream is either down, or very slow, Flask must wait until it errors out to return your webpage. 

IQooLogic's fix will workaround the issue instead of modifying the code. The DNS resolution for geospray.threatstream.com will instead resolve to localhost, which returns an immediate error of no response on the api call. Its not a permanent fix. 

You can use this command if you aren't familiar with Linux.
`echo "127.0.0.1	geospray.threatstream.com" >> /etc/hosts`

**Comment by Jdelgado89** [comment]
@z0n3z3r0 Thank you sir for that

**Comment by Wheaties466** [comment]
it looks like I am having a similar issue, It has stopped processing attacks but the honeymap seems to work but nothing is logging under sensors.

**Comment by f1r3walled** [comment]
Adding `127.0.0.1 geospray.threatstream.com` to `/etc/hosts`, also solved my problem.

**Comment by izm1chael** [comment]
> Adding `127.0.0.1 geospray.threatstream.com` to `/etc/hosts`, also solved my problem.

Can confirm that this works

**Comment by Norup123** [comment]
I did the above and can confirm it also worked for me, however the map no longer displays any attacks. Ive tried attacking my honeypots from vpns around the world. they show up on the attack page, but the map is completely blank. Is there another way to fix this without just disabling the geoip ?

**Comment by gamba** [comment]
This issue is becoming weird. I summarise:

- MHN attacks page depends from an external service on ```geospray.threatstream.com``` to return the country of an ip. 
- This service running on ```geospray.threatstream.com``` doesn't work. 

The bad: 
- each time you visit the attacks page on your MHN, you leak to ```geospray.threatstream.com``` the IP of the hosts you recorded as attackers. 

The ugly: 
- you can quickly put a patch on this problem by preventing MHN to contact ```geospray.threatstream.com``` by editing your /etc/hosts. This approach is no solution,...

The good: 
- MHN comes with all you need to resolve IP -> country without depending from an external service. A possible (working) solution has been submitted #698 , but - at this time - hasn't been merged.

**Comment by sikhan555** [comment]
Thanks  its help me alot. great...

**Comment by Norup123** [comment]
I suppose the issue here as Gamba said, is that it tries to contact a service that no longer exists. So the fix should be #698
I tested the solution and it works like a charm. So the problem is now that only 2 honeypots show up on the map

**Comment by irinicd** [comment]
I used the patch https://github.com/threatstream/mhn/pull/698/commits/0259996b97e6cca3a49898e24125f5f3df7d7823 and it did resolve the issue, for a while. 

My main problem is that is make a request to the MHN api (e.g. $wget "mhn_url/api/feed/?api_key=$mhn_api_key&channel=dionaea.capture&hours_ago=24") and again, I get a timeout.
