### ISSUE TITLE
Honeymap Issue -  All sensor events,except for elastichoney events, are not displayed. 

### ISSUE THREAD

**Issue by jtsamas** [pwnlandia/mhn#704]
I reinstalled the System ON Ubuntu 16.04 TLS, about a week ago... if you visit the elastic sensor IT will generate attack events on the honeymap.... However no events for cowrie, wordpot, conport or other sensors. 

:~$ sudo supervisorctl status
amun                             RUNNING   pid 22301, uptime 0:00:49
conpot                           STARTING
cowrie                           RUNNING   pid 22303, uptime 0:00:49
elastichoney                     RUNNING   pid 22288, uptime 0:00:49
geoloc                           RUNNING   pid 22295, uptime 0:00:49
honeymap                         RUNNING   pid 22310, uptime 0:00:49
hpfeeds-broker                   RUNNING   pid 22289, uptime 0:00:49
mhn-celery-beat                  RUNNING   pid 22285, uptime 0:00:49
mhn-celery-worker                RUNNING   pid 22302, uptime 0:00:49
mhn-collector                    RUNNING   pid 22309, uptime 0:00:49
mhn-uwsgi                        RUNNING   pid 22298, uptime 0:00:49
mnemosyne                        RUNNING   pid 22291, uptime 0:00:49
p0f                              RUNNING   pid 22399, uptime 0:00:48
snort                            RUNNING   pid 22311, uptime 0:00:49
suricata                         RUNNING   pid 22287, uptime 0:00:49
wordpot                          RUNNING   pid 22296, uptime 0:00:49

I noticed that the july update to deploy_snort.sh cause this error when run

+ '[' 2 -ne 2 ']'
++ echo 'eth0
eth1'
++ wc -w
+ compareint=2
+ '[' 'eth0
eth1' = 'e*' ']'
+ '[' 2 -ne 1 ']'
+ echo 'No Interface selectable, please provide manually.'
No Interface selectable, please provide manually.
+ echo 'Usage: deploy.sh <server_url> <deploy_key> <INTERFACE>'
Usage: deploy.sh <server_url> <deploy_key> <INTERFACE>
+ exit 1

The code below seems to the source of the problem:

**#!/bin/bash

INTERFACE=$(basename -a /sys/class/net/e*)

set -e
set -x

if [ $# -ne 2 ]
    then
        if [ $# -eq 3 ]
          then
            INTERFACE=$3
          else
            echo "Wrong number of arguments supplied."
            echo "Usage: $0 <server_url> <deploy_key>."
            exit 1
        fi

fi

compareint=$(echo "$INTERFACE" | wc -w)

if [ "$INTERFACE" = "e*" ] || [ "$compareint" -ne 1 ]
    then
        echo "No Interface selectable, please provide manually."
        echo "Usage: $0 <server_url> <deploy_key> <INTERFACE>"
        exit 1
fi**

So I changed all the scripts to the code below and I was able to deploy the sensors:

**#!/bin/bash

INTERFACE=eth0

set -e
set -x

if [ $# -ne 2 ]
    then
        echo "Wrong number of arguments supplied."
        echo "Usage: $0 <server_url> <deploy_key>."
        exit 1
fi**

So i can see the attacks on my admin dashboard though my only two problems now are 
1. Having the honeymaps display the attack events
2. establishing whether [geospray.threatstream.com](geospray.threatstream.com) is being used as it causes an error... I have implemented a bypass to resolve that url to 127.0.0.1 under /etc/hosts however this means the country flags under the dashboard will be reported as no flags.

**Comment by jtsamas** [comment]
RESOLVED

**Comment by d1str0** [comment]
What resolved this issue for you?
