### ISSUE TITLE
MHN Dashboard Not Login

### ISSUE THREAD

**Issue by sikhann** [pwnlandia/mhn#712]
Hi,

I was trying to login MHN dashboard, but no success. I try to reset the password on config.py file and did as per this  https://github.com/threatstream/mhn/wiki/MHN-Troubleshooting-Guide  but no success at all.
MHN dashboard display also change and honeymap is working fine and displaying the attacks activities.
![MHN dashboard no login](https://user-images.githubusercontent.com/31309975/65321369-73d2af80-dbbd-11e9-8c4d-d23e5972afd1.png)

Kindly help me regarding this issue. Thanks in advance.

Regards,

sikhann

**Comment by red-r3b3l** [comment]
I came here checking for a similar issue and was surprised to see it wasn't just me. After a clean install with no errors (though it wasn't the first install on my DigitalOcean Ubuntu server, the first few had odd misc. errors), and setting up a supervisor email and password, when accessing the dashboard my credentials don't seem to work.

I had pulled the repo from git only an hour or so ago, so its the latest version having this issue. 
![mhnerror](https://user-images.githubusercontent.com/31393975/66012948-4debbb80-e497-11e9-8b5b-cd8ae5f65c63.PNG)

**Comment by red-r3b3l** [comment]
> Hi,
> 
> I was trying to login MHN dashboard, but no success. I try to reset the password on config.py file and did as per this https://github.com/threatstream/mhn/wiki/MHN-Troubleshooting-Guide but no success at all.
> MHN dashboard display also change and honeymap is working fine and displaying the attacks activities.
> ![MHN dashboard no login](https://user-images.githubusercontent.com/31309975/65321369-73d2af80-dbbd-11e9-8c4d-d23e5972afd1.png)
> 
> Kindly help me regarding this issue. Thanks in advance.
> 
> Regards,
> 
> sikhann

@sikhan555 it seems like you might be using a different version of MHN from the screenshot though, am I right?

**Comment by sikhann** [comment]
Resolved..
