### ISSUE TITLE
Usage: add_user.py <ident> <secret> <publish> <subscribe>

### ISSUE THREAD

**Issue by Suhaila123** [pwnlandia/mhn#718]
After i add 
python add_user.py "$IDENT" "$SECRET" "$PUBLISH_CHANNELS" "$SUBSCRIBE_CHANNELS

i get this error Usage: add_user.py <ident> <secret> <publish> anyone please lead me to the right step. :)

**Comment by d1str0** [comment]
What are you trying to accomplish? You shouldn’t need the quotes. In fact you have a missing quote on the end.
