### ISSUE TITLE
pwnlandia/evnet repo doesn't exist

### ISSUE THREAD

**Issue by marcocen** [pwnlandia/mhn#719]
The change of repo introduced in commit 24617e3f6a0d77bfbedb232222788db6d7b1c052 breaks the installation, as that link 404s.

The old link seems to work, is the plan to fork the original repo?

**Comment by d1str0** [comment]
Do you know which links 404? There are 3 changed in that commit. 

I have yet to run a full test pass.

**Comment by d1str0** [comment]
Ok so it’s the evnet project. 

I will either transfer or fork this today. 

Thanks for pointing this out!

**Comment by d1str0** [comment]
@marcocen i just forked the project. Would you be able to test and report?

**Comment by marcocen** [comment]
I'm currently testing only the install_hpfeeds.sh script, as I'm trying to add support for centos7, but this particular error is resolved.

Thanks!

**Comment by d1str0** [comment]
Good luck on centos7, I’ve yet to have any luck with it. My main issue was nginx configuration was impossible to get right and troubleshoot.
