### ISSUE TITLE
ERROR (abnormal termination) - mnemosyne & hpfeeds-broker

### ISSUE THREAD

**Issue by Arnaud-Burn** [pwnlandia/mhn#73]
Hi guys !

Just did a fresh install on Ubuntu Server 14.04 and get this error :
" FATAL - ERROR (abnormal termination)"
on mnemosyne & hpfeeds-broker (others are good).

Tryed to stop/start but still the same problem.

Thanks for your help !

**Comment by akmallatiff** [comment]
Ok, found the problem !

It was Mongodb which was configured to journalize in a bad place (so there was insufficient free space on this folder).

I've changed it into the .conf file and now MHN is working again


somebody please help me how to fix like that?
sorry i'm newbies

**Comment by alifayyazhussain** [comment]
Hi, I installed MHN as per mentioned direction on Gihub/threastram mhn.........
but the out is only honeymap.!
no hpfeeds broker, no mnomosyne, 
please can any one help me
