### ISSUE TITLE
MHN(Modern Honey Network)'s country flags not work  

### ISSUE THREAD

**Issue by Sue1990** [pwnlandia/mhn#733]
I figured it out .....2019/11/22

**Comment by Sue1990** [comment]
Now, I find the log that shows something like this "2019-11-17 18:23:26,22 - ./mhn/ui/utils.py - Could not determine flags for IP: A.B.C.D" 

I tried " https://groups.google.com/forum/#!msg/modern-honey-network/tieU_eHlhuY/fK8lnm32PaoJ", but it still not work

**Comment by mgarzon** [comment]
> I figured it out .....2019/11/22

Was this a MHN bug or a configuration issue?

**Comment by Sue1990** [comment]
@mgarzon configuration issue

**Comment by mgarzon** [comment]
@Sue1990 I am having the same issues. I see the attacks coming but not the flags (or events in the honeymap). Could you please share how you fixed it?

**Comment by Sue1990** [comment]
@mgarzon you could try this --> https://github.com/pwnlandia/mhn/commit/0259996b97e6cca3a49898e24125f5f3df7d7823

Honeymap is real-time,if not error on the map page , just can't see attack,you may open new windows and wait for someone attack
