### ISSUE TITLE
View More data for WebApp Sensors

### ISSUE THREAD

**Issue by erwanlr** [pwnlandia/mhn#740]
Is there a way to view/add more data about the attacks ?

I've setup a MHN with a Wordpot sensor, but the data displayed is quite limited (ie Attacker IP, Port etc.).

In case of web app sensors (such as wordpot), it would be useful to have other info like URL, User Agent, Request Parameters (POST / GET) as well as credentials sent for pwd attacks.

**Comment by erwanlr** [comment]
Just saw that there was support for ELK at some point, but the versions are quite outdated. Any plan to update them ?

**Comment by d1str0** [comment]
PRs are welcome. :)

The ELK logs will hold all the data sent back from the honeypot applications. If there are fields you want to see but don’t, the honeypot might not be sending them. 

Also, of course other things like Gravwell will be able to ingest those logs easily.

**Comment by erwanlr** [comment]
Sent a PR to have the script up to date.

Unfortunately, even when other data is sent via HPFeeds, it's not written in the log, so there is something else going on here.

**Comment by d1str0** [comment]
@erwanlr we will need to update hpfeeds-logger if we want more data to show up.
