### ISSUE TITLE
ubuntu - cowrie deploy script fails on python error 

### ISSUE THREAD

**Issue by dsdameron** [pwnlandia/mhn#749]
I stood up an Ubuntu 16.04.6 LTS system and updated to latest patches.  I attempted to deploy cowrie's deploy script, but the build fails with the following error:

`Collecting pyasn1<0.5.0,>=0.4.6
  Downloading https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl (77kB)
     |████████████████████████████████| 81kB 6.6MB/s 
Requirement already satisfied: setuptools in ./cowrie-env/lib/python2.7/site-packages (from zope.interface>=4.4.2->twisted>=17.1.0->-r requirements.txt (line 1)) (45.0.0)
ERROR: Package 'setuptools' requires a different Python: 2.7.12 not in '>=3.5'`

I've tried removing the setup tools  package provided by ubunutu, installing with pip, etc but I cannot resolve this problem.  Any assistance is appreciated.

**Comment by dsdameron** [comment]
[Full Console output  of Deploy Attempt.txt](https://github.com/pwnlandia/mhn/files/4067465/Full.Console.output.of.Deploy.Attempt.txt)

**Comment by kevthehermit** [comment]
This is an issue with setuptools and virtualenv on python 27 not strictly with MHN. You can see the issue here https://github.com/pypa/virtualenv/issues/1493

You can try `pip install --upgrade 'setuptools<45.0.0'`

Although i am pretty sure cowrie is python3 compatible so the entire script should be updated

**Comment by dsdameron** [comment]
Thank you kevthehermit, this resolved my problem.  Running  `pip install --upgrade 'setuptools<45.0.0'`  as a standalone command did not resolve my issue.  However,  adding `pip install 'setuptools<45.0.0'` before `pip install -r requirements.txt` of the deployment script did.

**Comment by wrharding** [comment]
MHN no longer supports Ubuntu 16.04. Issue resolved for user.
