### ISSUE TITLE
ImportError caused by the Werkzeug lib updated

### ISSUE THREAD

**Issue by cwsu** [pwnlandia/mhn#752]
Hi,
I'm trying to install MHN server using this command 
`bash install_mhnserver.sh`
I get the ImportError: No module named contrib.atom.

I found that the **Werkzeug** lib is updated to version **1.0.0**
There are two problems due to the update.

1. `from werkzeug import url_encode` need to modify to  `from werkzeug.urls import url_encode`

2. The **atom** is deprecated. And they suggest that "This did not fit in with the rest of Werkzeug, and is better served by a dedicated library in the community."

![圖片](https://user-images.githubusercontent.com/6245473/74020678-0a6d0500-49d5-11ea-953b-7bdd9815b8d9.png)

Does anyone have any idea how to fix it?
 Thank you

**Comment by ttarnowski** [comment]
You need to update requirements.txt file and lock Werkzeug library to 0.16.1
Have a look at my PR: https://github.com/pwnlandia/mhn/pull/753

**Comment by d1str0** [comment]
I think this is resolved?
