### ISSUE TITLE
mhn-celery-worker Exited too quickly (process log may have details)

### ISSUE THREAD

**Issue by Clear2020** [pwnlandia/mhn#755]
mhn-celery-worker Exited too quickly (process log may have details)
log is AttributeError: 'exceptions.ImportError' object has no attribute 'name'

**Comment by d1str0** [comment]
What OS are you on? What server/hosting provider are you using?

When did this problem first occur? Is this on a fresh installation?

**Comment by wrharding** [comment]
No response from user for further troubleshooting.
