### ISSUE TITLE
Deploy Command issues

### ISSUE THREAD

**Issue by s4m0ur41** [pwnlandia/mhn#756]
Hi there,

wget "http://xx.xx.xx.xx/api/script/?text=true&script_id=4" -O deploy.sh && sudo bash deploy.sh http://xx.xx.xx.xx KEY

Each time I want to execute a deploy command using my WAN firewall (checkpoint) IP address interface (facing ISP router) it fails saying that it can not deal with the self-sign certificate.  All NAT and Foward Rules are fonctionnal. 
I tried the --no-check-certificate but it still does not work.
If I use the Internal IP address (DMZ) it works fine. But the sensor seems to be associated to this internal IP address which I guess prevent me to see Internet attacks.

Any help would be very welcome.
Thank you and have a nice day.

**Comment by d1str0** [comment]
This is outside the scope of MHN, and therefore not an issue.

Did you set up HTTPS on MHN? Or is your firewall improperly forwarding you somewhere else? When you use --no-check-certificate, what happens?
