### ISSUE TITLE
GPG error while install MHN

### ISSUE THREAD

**Issue by wkssd** [pwnlandia/mhn#760]
While running` ./install`，occur the error:
 E: GPG error: http://downloads-distro.mongodb.org dist InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)

This means I can't continue with the installation. Is there any way I can fix this? I am completely lost.

I try solve it by running `sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927`
but the error still ,

Thanks in advance for your help.

**Comment by d1str0** [comment]
What OS are you attempting to install on?

**Comment by wkssd** [comment]
I install it on Ubuntu 18.04. I have solved this problem, thank you for your concern about my problem.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Brady Sullivan"<notifications@github.com&gt;; 
发送时间: 2020年4月23日(星期四) 凌晨5:01
收件人: "pwnlandia/mhn"<mhn@noreply.github.com&gt;; 
抄送: "me"<1411734207@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pwnlandia/mhn] GPG error while install MHN (#760)





 
What OS are you attempting to install on?
