### ISSUE TITLE
./registration.sh failed to resolve host address 'http'

### ISSUE THREAD

**Issue by SuzukiCode** [pwnlandia/mhn#762]
Greetings,

When I deploy Dionaea I get the following error in the deploy.sh script at the end of the install:

+wget http:192.168.1.134/static/registration.txt -O registration.sh
--2020-03-24 14:30-- ftp://http/192.168.1.134/static/registration.txt
                         => 'registration.sh'
Resolving http (http)... failed: Name or service not known.
wget: unable to resolve host address 'http'

Please help!

Thanks,

Suzuki

**Comment by d1str0** [comment]
What is the deploy command you are given? You have a stray ftp:// in there

**Comment by SuzukiCode** [comment]
wget "http://192.168.1.134/api/script/?text=true&script_id=2" -O deploy.sh && sudo bash deploy.sh http://192.168.1.134 OgTvEvEi

**Comment by SuzukiCode** [comment]
@d1str0 this is what is generated in the deploy.sh file for that particular part:

wget $server_url/static/registration.txt -O registration.sh
chmod 755 registration.sh
# Note: this will export the HPF_* variables
. ./registration.sh $server_url $deploy_key "dionaea"

**Comment by d1str0** [comment]
What OS and what shell are you trying to install on?

As you can see, your error stems from wget trying to fetch over ftp:// not http://

"wget http:192.168.1.134/static/registration.txt -O registration.sh"

For some reason your first post has this, which is missing // after http:

**Comment by SuzukiCode** [comment]
@d1str0 So I replaced "wget $server_url" with 192.168.1.134 and it went all the way to the end of the registration.sh file and ends at this line: } 'http:/192.168.1.134/api/sensor
then it exits instead of updating hpfeeds or updating supervisor.

I'm installing it on Ubuntu 14.04(x32)

**Comment by d1str0** [comment]
So you can still see that it's putting http:/192 and not http://192

Something is screwing up the command because it's cutting out the slashes.

Also, Ubuntu14 is EOL and has been for a while. If you have the ability, please use 16 or 18. Tbh, 14 just isn't supported.

**Comment by d1str0** [comment]
I'll keep helping you troubleshoot this a bit, but I have no plans to implement a fix if it's only applicable to Ubuntu 14. Closing this issue for now but if it persists in newer versions of Ubuntu we can reopen.

**Comment by SuzukiCode** [comment]
Installing on Ubuntu 18.04 worked. Thank you for your assistance
