### ISSUE TITLE
python2.7 not support now , glastopf has error

### ISSUE THREAD

**Issue by Sue1990** [pwnlandia/mhn#765]
when I try to install glastopf I got something wrong, and  I try to fix it . In the script I changed python to python3 . It will show the error below  the picture. Has anyone can resovle this problem ?
![截圖 2020-04-19 下午6 24 02](https://user-images.githubusercontent.com/39720327/79685392-227dc200-826b-11ea-8eed-835a1e311a7d.png)

**Comment by d1str0** [comment]
Simply changing it to use python3 will not work. There will surely be extra work needed to be done. There is a backlog of python2 to 3 migration work to be done. I have no timeline for completing this right now.

**Comment by opliyal3** [comment]
Me too my Cowrie is not support python2
finally I modify the script to use that

**Comment by d1str0** [comment]
@opliyal3 any PRs youre willing to provide would be welcomed.

**Comment by opliyal3** [comment]
@d1str0 

I've already finished
