### ISSUE TITLE
"This site can't be reached" after fresh install

### ISSUE THREAD

**Issue by Mark40063795** [pwnlandia/mhn#771]
Fresh install on ubuntu 16.04 which seemed to work, opted to install uwf too.

According to 'supervisorctl status' all of the services are running fine. But when i try to go to the dashboard with http://{server IP} i get a "This site can't be reached" error. Tried with multiple browsers. Double checked to make sure the uwf rules were set to open from anywhere. Tried disabling uwf. Restarted multiple times. Nothing seems to work to get access.

Any ideas anyone?

Edit: And yes the ip is correct

**Comment by d1str0** [comment]
Cloud host? Local machine or cloud provider? If cloud, which host?

**Comment by Mark40063795** [comment]
Ah sorry, Cloud host. AWS EC2 machine

**Comment by Mark40063795** [comment]
Actually I hadn't considered the cloud host was the issue, my bad. By default AWS only allows SSH, had to allow http traffic for it to work
