### ISSUE TITLE
No payloads recorded after using script deployment

### ISSUE THREAD

**Issue by Mark40063795** [pwnlandia/mhn#772]
So my current setup is that i have mhn installed on a VM, hosted on AWS using ubuntu 16.04. ,Then I have two honeypot vm's hosted on google cloud which also use ubuntu 16.04.

My firewall set up is as follows:

- Both honeypot VM's are completely open on all ports

- AWS dashboard VM allows traffic only on ports 10000 & 445 from the honeypot VM IP's

- AWS dashboard allows connections from ports 22, 80, 443, 3000 from my personal IP

To install the honeypots I used the "Ubuntu/Raspberry Pi - Dionaea" deployment script from the mhn dashboard. This seems to have worked as i can see them both in my list of sensors and I'm getting a constant stream of attacks on both. However, I'm not getting any payloads recorded even after i used `namp -A {honeypot ip}` from a separate kali vm targeting the honeypot IP's, which generated roughly 30,000 attacks and showed that all ports are open and they are vulnerable.

Now here is where it seems to be different from other peoples issues. I initially tried to install and connect dionaea myself which failed so i just used the deployment script. But, now when i use  `sudo supervisorctl status` the only thing that is there is a service called dionaea, NOT this list that other people seem to have 

![image](https://user-images.githubusercontent.com/36634446/82833610-62f9dc80-9eb6-11ea-9559-36470d611d9f.png)

If the binaries are stored in /var/dionaea/binaries then that's an issue. There is no dionaea directory in /var for me on either honeypot VM or the dashboard VM.

Also i have tried the sugestions that are in this thread https://github.com/pwnlandia/mhn/issues/417 but as many relate to /var/dionaea I can't try them all

I'm not really sure what to try now, any help would be greatly appreciated

**Comment by Mark40063795** [comment]
I decided to delete it all and start again because i crashed my ec2 vm by mistake and it wouldn't reboot so moved to azure for their free trial lol.

Same basics setup and the services appear to be correct yet i still have no payloads. Are there more ports that need to be opened between the honeypot server and the dashboard server than 10000 and 445?

**Comment by d1str0** [comment]
Payload functionality has been broken for a while. They should be sent over 10000 (hpfeeds), but they aren't be saved by MHN right now.

Duplicate of #422

**Comment by d1str0** [comment]
Do you have any trouble seeing attacks?

**Comment by Mark40063795** [comment]
No the attacks are listed fine, i think. So if the payloads are broken on the dashboard, where would the payloads be downloaded to by default. On the honeypot VM or the dashboard VM?

**Comment by debus** [comment]
Test

**Comment by d1str0** [comment]
The VM would have it if dionaea still supports payloads/binaries. Also, check /opt/dionaea/var/dionaea

**Comment by Mark40063795** [comment]
Ahh, it seems they have moved where its stored slightly. It's in /opt/dionaea/var/lib/dionaea/binaries. Its empty for me at the moment and so is the downloads table of the database.

even after executing a few vulnerabilities through metasploit they are still empty, so its an issue with dionaea rather than mhn
