### ISSUE TITLE
Docker Version not work

### ISSUE THREAD

**Issue by wcc526** [pwnlandia/mhn#777]
root@3644a7bf6576:/# ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0   3968  1608 ?        Ss   02:31   0:00 /bin/bash /entrypoint.sh
root        260  0.1  0.2  27836 19108 ?        S    02:31   0:00 /usr/bin/python3 /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
root        262  0.0  0.0   4232  2284 ?        Ss   02:31   0:00 /bin/bash
root        279  0.0  0.0   5872  1476 ?        R+   02:33   0:00 ps aux
root@3644a7bf6576:/# supervisorctl restart all
mongod: ERROR (no such file)
nginx: ERROR (no such file)

**Comment by d1str0** [comment]
Yes, please do not use Docker version at this time.
