### ISSUE TITLE
No Attack Report after Scanning - [MHN - CONPOT]

### ISSUE THREAD

**Issue by utku461** [pwnlandia/mhn#781]
Hey Guys, 

i fully installed MHN on my vm. Furthermore i deployed conpot unfortunately i did some nmap scans but i get 0 Attack reports. I used to watch the troubleshoot guide but with no luck. Maybe someone can help me

**Comment by d1str0** [comment]
Conpot is an industrial control system honeypot. A simple nmap will likely not generate attacks

Cheers

Brady Sullivan
