### ISSUE TITLE
honeymap        FATAL     can't find command '/opt/honeymap/server/server'

### ISSUE THREAD

**Issue by zulfihidayat** [pwnlandia/mhn#822]
Hallo i found this issue [honeymap        FATAL     can't find command '/opt/honeymap/server/server']
when i check requires in honeymap go.mod, i can't find this repo github.com/fzzy/sockjs-go on github
can you provide the solution?

**Comment by wrharding** [comment]
Duplicate of #811 & #813, a new library will need to be found and implemented. For now, follow #811's solution of installing honeymap and installing independently.

**Comment by wrharding** [comment]
This was fixed in pwnlandia/honeymap#2
