### ISSUE TITLE
https://github.com/fzzy/sockjs-go error 404

### ISSUE THREAD

**Issue by anoma13** [pwnlandia/mhn#832]
honeymap.go:13:2: cannot find package "github.com/d1str0/hpfeeds" in any of:
	/usr/local/go/src/github.com/d1str0/hpfeeds (from $GOROOT)
	/home/lee/go/src/github.com/d1str0/hpfeeds (from $GOPATH)
honeymap.go:14:2: cannot find package "github.com/jt6211/sockjs-go/sockjs" in any of:
	/usr/local/go/src/github.com/jt6211/sockjs-go/sockjs (from $GOROOT)
	/home/lee/go/src/github.com/jt6211/sockjs-go/sockjs (from $GOPATH)

https://github.com/fzzy/sockjs-go error 404 , is there any workaround for this?

**Comment by wrharding** [comment]
See #813

**Comment by d1str0** [comment]
I believe this is fixed.
