### ISSUE TITLE
sensor snort does not report an attack in payloads

### ISSUE THREAD

**Issue by Axel383** [pwnlandia/mhn#834]
I installed a raspberry PI and use the wget command to deploy a sensor snort on my local network, I then install my sensor in my dmz by changing the network configuration but no attack goes back. Do you have an idea of ​​the problem ?
Thanks

**Comment by Axel383** [comment]
my firewall block communications between my raspberry and the mhn server I will add a rule allowing traffic to pass do you know which port is used for communication between the mhn server and the sensor snort?

**Comment by d1str0** [comment]
It would need to connect with hpfeeds to port 10000.

**Comment by d1str0** [comment]
Closing as this is a setup issue.
