### ISSUE TITLE
is it possible to run this on my raspberry pi? it is ubuntu-based....

### ISSUE THREAD

**Issue by festheray** [pwnlandia/mhn#837]
I get the following error 
`pymongo.errors.ConfigurationError: Server at localhost:27017 reports wire version 0, but this version of PyMongo requires at least 2 (MongoDB 2.6).`

... also is there plan to upgrade from py 2 => py 3? Is that something we can contribute to?

**Comment by wrharding** [comment]
Installing MHN on an RPi was being worked on in #688. Currently, only the Dionea honeypot deploy script supports RPi deployment:

https://github.com/pwnlandia/mhn/wiki/Deploying-Dionaea-on-a-Raspberry-Pi

As for moving from Python 2.7 to Python 3, I’ve been thinking of making an issue detailing what needs to be upgraded for such a move. The MHN maintainer will need to be heavily involved for such an update.

**Comment by festheray** [comment]
ok thanks!
