### ISSUE TITLE
Issue when installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by SplunkMaster69** [pwnlandia/mhn#842]
As of yesterday, any installation of MHN is broken. When running ./install.sh gets about halfway done, prior to the prompts, it spits out this error "ImportError: No module named collections_abc".

**Comment by wrharding** [comment]
Are you able to provide a more detailed output of the error, when it occurred during installation and what work arounds you've tried?

**Comment by wrharding** [comment]
Not enough information provided.
