### ISSUE TITLE
Raspberry Pi - Dionaea - Services Not Running and No Local Logs

### ISSUE THREAD

**Issue by 0xdeadbeefJERKY** [pwnlandia/mhn#94]
I followed the "Deploying Dionaea on Raspberry Pi" guide several times in great detail, but whenever I run an nmap from another machine or a netstat on the honeypot itself, nothing more than the SSH service is displayed. The nmap attacks are being fed properly to the MHN feeds and displayed via the web interface, but Dioanea is not logging anything locally (there's no dionaea.log file created anywhere on the file system). I'm wondering if it's because Dionaea is installing in the following manner:

/opt/dionaea/bin
/opt/dionaea/etc
/opt/dionaea/var
...
Instead of:
/bin/dionaea
/etc/dionaea
/var/dionaea (or /var/log/dionaea)
...

I've also tried editing the dionaea.conf file (according to the other Issues post), removing http/https from the services->serve array, "adding ipv4" via "0.0.0.0" in the listen->addrs array, etc.

**Comment by HallefHerbeth** [comment]
friends, I'm trying to use the raspberry pi dionaea, I'm having the same problem ...

The dionaea registers the attacks on the mhn server, but is not saving local no binary or record type.
